### Login And Get Token
POST http://localhost:3000/login
content-type: application/json

{
    "email": "admin@email.com",
    "password": "standard4499"
}

### Get Users
GET http://localhost:3000/users
Authorization: token <YOUR-API-TOKEN>

### Get User data from a user
GET http://localhost:3000/users/<ID-USER>
Authorization: token <YOUR-API-TOKEN>

### POST USERS
POST http://localhost:3000/users
content-type: application/json
Authorization: token <YOUR-API-TOKEN>

{
"name": "New User Name Example",
"email": "newUser@gmail.com",
"password": "1234NewUser069",
"longest_race": 10
}

###GET RACES
GET http://localhost:3000/races
Authorization: token <YOUR-API-TOKEN>

###POST RACES
POST http://localhost:3000/races
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiIwZTQ3OTVjMS0zYmY3LTRjYzctODcwMC04M2EwNGM5ODA4OTciLCJpYXQiOjE3NTY3NTA4MTUsImV4cCI6MTc1Njc1NDQxNX0.boucBXbr1JTBSV9QX7toEeGu3W0iuBTNnxm0v7RPAkA

{
  "race_time": "00:30:00",
  "distance": 8,
  "date": "2025-08-29"
}
