###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
content-type: application/json

{
    "name": "Caique Kevin Mendes",
    "email": "caique405@gmail.com",
    "password": "1234caique",
    "longest_race": 10
}