## Baixar a imagem do node
FROM node:lts-slim

## Definir o dirétório de trabalho
WORKDIR /server

## Copiar o package.json e package-lock.json
COPY ./package.json package-lock.json* .


## Instala as dependencias
RUN npm install

## Copiar o restante do projeto
COPY . .

## Roda api e faz migrations no banco de dados
CMD ["sh", "-c", "npx drizzle-kit migrate && npm run db:seed && npm run container:dev"]