## Baixar a imagem do node
FROM node:22

## Definir o dirétório de trabalho
WORKDIR /server

## Copiar o package.json e package-lock.json
COPY ./package.json package-lock.json* .

## Copiar o restante do projeto
COPY . .

## Roda api e faz migrations no banco de dados
CMD ["sh", "-c", "npm install && npx drizzle-kit migrate && npm run db:seed && npm run dev"]