FROM node:22

WORKDIR /server

COPY ./package.json package-lock.json* .

RUN npm install

COPY . .

COPY ./.env  .

EXPOSE 3000

#Dentro da pasta SERVER - Executa quando inicia o container
#CMD ["npm", "run", "dev"]